### PR TITLE
setup TravisCI

### LINKED ISSUE #21: setup TravisCI
The GitHub-hosted scuff-em repository needs to use TravisCI for continual checking of build success on various platforms.

### PR DESCRIPTION
**Pull request by jfeist**
initial shot at setting up TravisCI - should close #21.

In my github fork, this works and the build passes. I also updated README.md to include the badge that shows that the current build is passing. The URL I used should be the correct one once it is set up in the main repository (HomerReid/scuff-em) for the master branch.

Homer, before doing anything else, you should probably enable travis for the repository (after signing into travis with github, it is only a few clicks). When you merge the PR, it should automatically notice that there is a new commit and run the build. I'm not sure if it will run directly for the pull request as soon as you enable travis, or if you have to change something first (push a new commit, merge the PR, ...).

### CODE REVIEW

**Comment by jfeist** [comment]
BTW - the simple setup in this build request right now only _builds_ scuff-em, it does not test anything. Obviously, it would be good to add that as well (as you already mentioned in #22). I noticed that `make check` does run some tests, but at least for me some of those always fail. Also, it would be good to include a small test of the python interface there (at least to check that `import scuff` works). I'd be happy to contribute something there as well, but haven't had time to check how it all works yet.

**Comment by HomerReid** [comment]
Johannes, thanks a million! This has been on my to-do list forever, and getting this working is a crucial milestone towards the creation of a proper release. It's way past time to have some simple unit tests running to catch regressions, the finding and fixing of which has been a major waste of time for years, most recently in conjunction with issue #40.

I will follow your instructions to enable TravisCI for the repository, then check in some simple tests that actually *do* pass. Then I will probably switch over to a model, like you suggest, in which the "master" branch of the repository is maintained in a pristine, guaranteed-buildable state, while I maintain my own local working repositories on separate branches called "devel" or "unstable" or something.

I agree that unit-testing the python interface is important, since that has traditionally been a place in which minor compilation-preventing bugs tend to accumulate without my noticing it. 

Thanks again for inaugurating this major step forward.

**Comment by jfeist** [comment]
I just rebased this to the latest master. It would be great if you could merge it - it is working as is. You just have to enable travis for the repository (after signing into travis with github, it is only a few clicks), and then merge this PR.

**Comment by HomerReid** [comment]
Thanks again for starting this off. I hope this will help to eliminate the sort of annoying minor build errors you had to deal with yesterday.

**Comment by HomerReid** [comment]
The travis build is passing. Great news. Now I'll have an easier time figuring out when silly missing-file issues break the build.

https://travis-ci.org/HomerReid/scuff-em.svg?branch=master

**Pull request merged**
